eureka:
  client:
    register-with-eureka: true #网关不用注册到注册中心中，因为没其他微服务调用他
    fetch-registry: true #这个必须是true fetchRegistry打开才能从eureka拉取服务列表
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka



server:
  port: 8301
spring:
  application:
    name: zuul-01
zuul:
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  routes:
    api-a:
      path: /api-a/**
      serviceId: client-01
    api-b:
      path: /api-c/**
      serviceId: client-03
# 添加ribbon的超时时间设置
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 3000