spring:
  application:
    name: config
  #git 配置
  cloud:
    config:
      label: master #分支名，一般为master
      server:
        git:
          uri: https://github.com/erhu01/config  # 远程git仓库的地址
          search-paths: config  #仓库中的文件夹名
          username: erhu01  # 以及相应的账户名
          password: Xiong1991  # 和密码
          basedir: F:\gitPro\config  # 可以使用这个配置项来指定本地git仓库的路径
#访问一下地址
#http://localhost:8401/application-client-01.yml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
server:
  port: 8401